/*
 * Copyright (c) 2026, PostgreSQL Global Development Group
 * See the LICENSE file in the project root for more information.
 */

package org.postgresql.jdbc.codec;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * The currency symbols of the locales that print three fraction digits.
 *
 * <p>{@code money} reaches the driver as the server's {@code lc_monetary} rendering, and one
 * rendering cannot be read from its own shape: a single separator with exactly three digits after
 * it and one to three before, {@code 1,234}, is 1234 where the locale prints no fraction and
 * 1.234 where it prints three. {@link MoneyCodec} consults this list to tell those apart, and only
 * there &mdash; a locale printing two fraction digits cannot produce that rendering, because
 * {@code cash_out} always prints exactly {@code frac_digits} of them. That gate is what makes a
 * symbol shared with a two-fraction-digit currency, as {@code L} and {@code £} are, harmless.</p>
 *
 * <p>Generated by {@code docker/bin/currency-fraction-digits} from glibc 2.41-12+deb13u3; do not
 * edit by hand. Re-run it when the server images move to a new glibc.</p>
 */
final class MoneyFractionDigits {

  /** Symbols whose locale prints three fraction digits, longest first so a prefix cannot shadow. */
  private static final List<String> THREE = Collections.unmodifiableList(Arrays.asList(
      "ج.س.",           // U+062C U+002E U+0633 U+002E  ar_SD
      "ج.م.",           // U+062C U+002E U+0645 U+002E  ar_EG
      "د.أ.",           // U+062F U+002E U+0623 U+002E  ar_JO
      "د.إ.",           // U+062F U+002E U+0625 U+002E  ar_AE
      "د.ب.",           // U+062F U+002E U+0628 U+002E  ar_BH
      "د.ت.",           // U+062F U+002E U+062A U+002E  ar_TN
      "د.ج.",           // U+062F U+002E U+062C U+002E  ar_DZ, ber_DZ
      "د.ع.",           // U+062F U+002E U+0639 U+002E  ar_IQ
      "د.ك.",           // U+062F U+002E U+0643 U+002E  ar_KW
      "د.ل.",           // U+062F U+002E U+0644 U+002E  ar_LY
      "د.م.",           // U+062F U+002E U+0645 U+002E  ar_MA
      "ر.ع.",           // U+0631 U+002E U+0639 U+002E  ar_OM
      "ر.ق.",           // U+0631 U+002E U+0642 U+002E  ar_QA
      "ر.ي.",           // U+0631 U+002E U+064A U+002E  ar_YE
      "ل.س.",           // U+0644 U+002E U+0633 U+002E  ar_SY
      "ل.ل.",           // U+0644 U+002E U+0644 U+002E  ar_LB
      "ⴷ.ⵎ.",           // U+2D37 U+002E U+2D4E U+002E  ber_MA
      "Nu.",            // U+004E U+0075 U+002E  dz_BT
      "د.ع",            // U+062F U+002E U+0639  ckb_IQ
      "ⴷ.ⵎ",            // U+2D37 U+002E U+2D4E  zgh_MA
      "L",              // U+004C  sq_AL
      "£"));            // U+00A3  ar_SS

  private MoneyFractionDigits() {
  }

  /**
   * Whether {@code literal} carries the symbol of a currency that prints three fraction digits.
   *
   * @param literal the money literal as the server rendered it
   * @return {@code true} if the literal names such a currency
   */
  static boolean printsThreeFractionDigits(CharSequence literal) {
    String text = literal.toString();
    for (int i = 0, size = THREE.size(); i < size; i++) {
      if (text.contains(THREE.get(i))) {
        return true;
      }
    }
    return false;
  }
}
