/*
 * Copyright (c) 2026, PostgreSQL Global Development Group
 * See the LICENSE file in the project root for more information.
 */

package org.postgresql.test.codec;

import static org.junit.jupiter.api.Assertions.fail;
import static org.postgresql.test.codec.CodecTestSupport.CTX;
import static org.postgresql.test.codec.CodecTestSupport.type;

import org.postgresql.core.Oid;
import org.postgresql.jdbc.PgType;
import org.postgresql.jdbc.codec.ByteaCodec;

import org.instancio.Instancio;
import org.instancio.junit.InstancioExtension;
import org.instancio.junit.Seed;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Variable-length codec property test using {@code bytea} as a self-contained example
 * ({@code decodeBinary} is a defensive copy, so the roundtrip is the identity).
 *
 * <p>This is where the user's point about shrinking applies: for variable-length types a random
 * counterexample can be large. Two mitigations are demonstrated:</p>
 * <ol>
 *   <li><b>Bound the generated size</b> ({@link #MAX_LEN}) so counterexamples are small by
 *       construction; and</li>
 *   <li>On failure, run {@link Minimizer} to delta-debug the failing array down to a minimal
 *       counterexample before reporting it — a manual stand-in for a PBT framework's shrinker.</li>
 * </ol>
 */
@ExtendWith(InstancioExtension.class)
class ByteaVariableLengthPropertyTest {

  private static final long SEED = 20260625L;
  private static final int MAX_LEN = 64;     // keep counterexamples small for variable-length data
  private static final int CASES = 300;
  private static final PgType BYTEA = type("bytea", "bytea", Oid.BYTEA);

  @Test
  @Seed(SEED)
  void byteaBinaryRoundtrips() throws Exception {
    for (int i = 0; i < CASES; i++) {
      byte[] input = randomBytes();
      if (!Arrays.equals(input, roundtrip(input))) {
        // Shrink before reporting so the failure is readable even for long inputs.
        byte[] minimal = Minimizer.shrink(input, ByteaVariableLengthPropertyTest::roundtripChanges);
        fail("bytea roundtrip failed; minimal counterexample: " + Minimizer.describe(minimal));
      }
    }
  }

  /** A bounded, Instancio-generated byte array (length in {@code [0, MAX_LEN]}). */
  private static byte[] randomBytes() {
    int len = Math.floorMod(Instancio.create(Integer.class), MAX_LEN + 1);
    List<Byte> bytes = new ArrayList<>(Instancio.ofList(Byte.class).size(len).create());
    byte[] out = new byte[len];
    for (int i = 0; i < len; i++) {
      out[i] = bytes.get(i);
    }
    return out;
  }

  private static byte[] roundtrip(byte[] input) {
    try {
      byte[] wire = ByteaCodec.INSTANCE.encodeBinary(input, BYTEA, CTX);
      return (byte[]) ByteaCodec.INSTANCE.decodeBinary(wire, BYTEA, CTX);
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }

  private static boolean roundtripChanges(byte[] input) {
    return !Arrays.equals(input, roundtrip(input));
  }
}
